# Data Cleaning

In [2]:
import pandas as pd

## Total GHG Dataset

In [3]:
total_ghg = pd.read_csv('datasets/factors/total-ghg-emissions.csv')

In [4]:
total_ghg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35226 entries, 0 to 35225
Data columns (total 4 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Entity                           35226 non-null  object
 1   Code                             34200 non-null  object
 2   Year                             35226 non-null  int64
 3   Annual greenhouse gas emissions  35226 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ MB

In [5]:
total_ghg_country = total_ghg[[len(str(x)) == 3 for x in total_ghg['Code']]]

In [6]:
total_ghg_without_iso = total_ghg_country[total_ghg_country['Code'].isna()]

In [7]:
total_ghg_world = total_ghg[total_ghg['Entity'] == 'World']

In [8]:
total_ghg_country = total_ghg_country.dropna()

In [9]:
total_ghg_country

            Entity Code  Year  Annual greenhouse gas emissions
0      Afghanistan  AFG  1851                        7373214.5
1      Afghanistan  AFG  1852                        7422393.5
2      Afghanistan  AFG  1853                        7483595.5
3      Afghanistan  AFG  1854                        7532321.0
4      Afghanistan  AFG  1855                        7580708.5
...            ...  ...   ...                              ...
35221     Zimbabwe  ZWE  2017                       37999464.0
35222     Zimbabwe  ZWE  2018                       39079344.0
35223     Zimbabwe  ZWE  2019                       38701420.0
35224     Zimbabwe  ZWE  2020                       37733230.0
35225     Zimbabwe  ZWE  2021                       38060004.0

[34029 rows x 4 columns]

In [10]:
total_ghg_without_iso

        Entity Code  Year  Annual greenhouse gas emissions
855    Annex I  NaN  1851                     2.269137e+09
856    Annex I  NaN  1852                     2.301952e+09
857    Annex I  NaN  1853                     2.354308e+09
858    Annex I  NaN  1854                     2.428702e+09
859    Annex I  NaN  1855                     2.445340e+09
...        ...  ...   ...                              ...
23764     OECD  NaN  2017                     1.559025e+10
23765     OECD  NaN  2018                     1.568621e+10
23766     OECD  NaN  2019                     1.532443e+10
23767     OECD  NaN  2020                     1.416157e+10
23768     OECD  NaN  2021                     1.478845e+10

[1026 rows x 4 columns]

In [11]:
total_ghg_world

      Entity      Code  Year  Annual greenhouse gas emissions
34542  World  OWID_WRL  1851                     4.100721e+09
34543  World  OWID_WRL  1852                     4.156867e+09
34544  World  OWID_WRL  1853                     4.233854e+09
34545  World  OWID_WRL  1854                     4.308952e+09
34546  World  OWID_WRL  1855                     4.336073e+09
...      ...       ...   ...                              ...
34708  World  OWID_WRL  2017                     5.340529e+10
34709  World  OWID_WRL  2018                     5.406630e+10
34710  World  OWID_WRL  2019                     5.482132e+10
34711  World  OWID_WRL  2020                     5.258525e+10
34712  World  OWID_WRL  2021                     5.459319e+10

[171 rows x 4 columns]

In [12]:
print('Total GHG ALL Shape', total_ghg.shape)
print('Total Shape Country', total_ghg_country.shape)
print('Total Shape w/o ISO', total_ghg_without_iso.shape)
print('Total Shape World  ', total_ghg_world.shape)

Total GHG ALL Shape (35226, 4)
Total Shape Country (34029, 4)
Total Shape w/o ISO (1026, 4)
Total Shape World   (171, 4)

In [13]:
print('Checking Divisions:', (35226-34029-1026-171) == 0)

Checking Divisions: True

## Per Capita GHG Dataset

In [14]:
perCapita_ghg = pd.read_csv('datasets/factors/per-capita-ghg-emissions.csv')

In [15]:
perCapita_ghg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33558 entries, 0 to 33557
Data columns (total 4 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Entity                               33558 non-null  object
 1   Code                                 33558 non-null  object
 2   Year                                 33558 non-null  int64
 3   Greenhouse gas emissions per person  33558 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.0+ MB

In [16]:
perCapita_ghg_country = perCapita_ghg[[len(str(x)) == 3 for x in perCapita_ghg['Code']]]

In [17]:
perCapita_ghg_world = perCapita_ghg[perCapita_ghg['Entity'] == 'World']

In [18]:
print('Per Capita GHG ALL Shape    ', perCapita_ghg.shape)
print('Per Capita GHG Country Shape', perCapita_ghg_country.shape)
print('Per Capita GHG World Shape  ', perCapita_ghg_world.shape)

Per Capita GHG ALL Shape     (33558, 4)
Per Capita GHG Country Shape (33387, 4)
Per Capita GHG World Shape   (171, 4)

In [19]:
print('Checking Divisions:', (33558-33387-171) == 0)

Checking Divisions: True

In [20]:
perCapita_ghg_country.isna().sum()
# confirm no null values

Entity                                 0
Code                                   0
Year                                   0
Greenhouse gas emissions per person    0
dtype: int64

# Global Displacement Dataset

In [21]:
displacement = pd.read_excel('datasets/effects/IDMC_GIDD_disasters_internal_displacement_data_2021-1680745854911.xlsx')

In [22]:
weather_related_dis = displacement[displacement['Hazard Category'] == 'Weather related']
geo_related_dis = displacement[displacement['Hazard Category'] == 'Geophysical']
na_related_dis = displacement[displacement['Hazard Category'].isna()]

In [23]:
print('ALL Shape', displacement.shape)
print('Geo Shape', geo_related_dis.shape)
print('Wea Shape', weather_related_dis.shape)
print('NA Shape ', na_related_dis.shape)

ALL Shape (11140, 9)
Geo Shape (670, 9)
Wea Shape (10467, 9)
NA Shape  (3, 9)

In [24]:
print('Checking Division: ', (11140-670-10467-3) == 0)

Checking Division:  True

### Clean Weather Related Displacement

In [25]:
weather_related_dis.isna().sum()

ISO3                                 0
Country / Territory                  0
Year                                 0
Event Name                         436
Date of event (start)                0
Disaster Internal Displacements      0
Hazard Category                      0
Hazard Type                          0
Hazard Sub Type                    523
dtype: int64

In [26]:
weather_related_dis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10467 entries, 0 to 11139
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ISO3                             10467 non-null  object
 1   Country / Territory              10467 non-null  object
 2   Year                             10467 non-null  int64
 3   Event Name                       10031 non-null  object
 4   Date of event (start)            10467 non-null  object
 5   Disaster Internal Displacements  10467 non-null  int64
 6   Hazard Category                  10467 non-null  object
 7   Hazard Type                      10467 non-null  object
 8   Hazard Sub Type                  9944 non-null   object
dtypes: int64(2), object(7)
memory usage: 817.7+ KB

In [27]:
weather_related_dis

,ISO3,Country / Territory,Year,Event Name,Date of event (start),Disaster Internal Displacements,Hazard Category,Hazard Type,Hazard Sub Type
0,AB9,Abyei Area,2018,Abyie: Flood - 01/07/2018,2018-07-01T00:00:00Z,2,Weather related,Flood,Flood
1,AB9,Abyei Area,2019,Abyei: Flood - southern parts - 01/06/2019,2019-06-01T00:00:00Z,40000,Weather related,Flood,Flood
3,AFG,Afghanistan,2008,NaN,2008-08-01T00:00:00Z,180,Weather related,Flood,Flood
4,AFG,Afghanistan,2009,2009-000080,2009-01-01T00:00:00Z,25000,Weather related,Flood,Flood
6,AFG,Afghanistan,2010,2010-000077,2010-01-01T00:00:00Z,70000,Weather related,Flood,Flood
...,...,...,...,...,...,...,...,...,...
11135,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,1100,Weather related,Storm,"Storm, Tropical, Cyclone"
11136,ZWE,Zimbabwe,2021,Zimbabwe: Hailstorm - Manicaland (Mutare Rural...,2021-11-01T00:00:00Z,330,Weather related,Storm,Hailstorm
11137,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,270,Weather related,Storm,"Storm, Tropical, Cyclone"
11138,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,140,Weather related,Storm,"Storm, Tropical, Cyclone"
11139,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,140,Weather related,Storm,"Storm, Tropical, Cyclone"

In [28]:
weather_related_dis['Disaster Internal Displacements'].sum()

305598573

In [29]:
geo_related_dis['Disaster Internal Displacements'].sum()

36742248

In [30]:
print('Total Disaster Displacement:', 305598573+36742248)
# confirmed in the website

Total Disaster Displacement: 342340821

In [31]:
weather_related_dis

,ISO3,Country / Territory,Year,Event Name,Date of event (start),Disaster Internal Displacements,Hazard Category,Hazard Type,Hazard Sub Type
0,AB9,Abyei Area,2018,Abyie: Flood - 01/07/2018,2018-07-01T00:00:00Z,2,Weather related,Flood,Flood
1,AB9,Abyei Area,2019,Abyei: Flood - southern parts - 01/06/2019,2019-06-01T00:00:00Z,40000,Weather related,Flood,Flood
3,AFG,Afghanistan,2008,NaN,2008-08-01T00:00:00Z,180,Weather related,Flood,Flood
4,AFG,Afghanistan,2009,2009-000080,2009-01-01T00:00:00Z,25000,Weather related,Flood,Flood
6,AFG,Afghanistan,2010,2010-000077,2010-01-01T00:00:00Z,70000,Weather related,Flood,Flood
...,...,...,...,...,...,...,...,...,...
11135,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,1100,Weather related,Storm,"Storm, Tropical, Cyclone"
11136,ZWE,Zimbabwe,2021,Zimbabwe: Hailstorm - Manicaland (Mutare Rural...,2021-11-01T00:00:00Z,330,Weather related,Storm,Hailstorm
11137,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,270,Weather related,Storm,"Storm, Tropical, Cyclone"
11138,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,140,Weather related,Storm,"Storm, Tropical, Cyclone"
11139,ZWE,Zimbabwe,2021,"Madagascar, Mozambique; Zimbabwe; South Africa...",2021-01-19T00:00:00Z,140,Weather related,Storm,"Storm, Tropical, Cyclone"

In [32]:
weather_related_dis = weather_related_dis[['ISO3', 'Country / Territory', 'Year', 'Disaster Internal Displacements']].groupby(['Country / Territory', 'ISO3', 'Year']).sum().reset_index()
# Grouped according to country and aggregated by year

In [33]:
weather_related_dis

     Country / Territory ISO3  Year  Disaster Internal Displacements
0             Abyei Area  AB9  2018                                2
1             Abyei Area  AB9  2019                            40000
2            Afghanistan  AFG  2008                              180
3            Afghanistan  AFG  2009                            25000
4            Afghanistan  AFG  2010                            70000
...                  ...  ...   ...                              ...
1451            Zimbabwe  ZWE  2017                            10308
1452            Zimbabwe  ZWE  2018                             1066
1453            Zimbabwe  ZWE  2019                            52400
1454            Zimbabwe  ZWE  2020                              385
1455            Zimbabwe  ZWE  2021                             2338

[1456 rows x 4 columns]

## GHG Factors Dataset

In [34]:
ghg_factors = pd.read_csv('datasets/factors/owid-co2-data.csv')
ghg_factors_meta = pd.read_csv('datasets/factors/owid-co2-codebook.csv')

Check the industries contributing to GHG emissions

In [35]:
rows = ghg_factors_meta.shape[0]
for i in range(rows):
    print(ghg_factors_meta['column'][i], '-', ghg_factors_meta['description'][i])
    print()

country - Geographic location.

year - Year of observation.

iso_code - ISO 3166-1 alpha-3, three-letter country codes.

population - Population of each country or region.

gdp - Gross domestic product measured in international-$ using 2011 prices to adjust for price changes over time (inflation) and price differences between countries. Calculated by multiplying GDP per capita with population.

cement_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from cement, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cement_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from cement, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2 - Annual total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_growth_abs - Annual growth in total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_growth_prct - Annual percentage growth in total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc - Annual total production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc_growth_abs - Annual growth in total production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc_growth_prct - Annual percentage growth in total production-based emissions of carbon dioxide (COâ‚‚), including land-use change. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc_per_gdp - Annual total production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured in kilograms per dollar of GDP (2011 international-$). Production-based emissions are based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_including_luc_per_unit_energy - Annual total production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured in kilograms per kilowatt-hour of primary energy consumption. Production-based emissions are based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_per_capita - Annual total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_per_gdp - Annual total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured in kilograms per dollar of GDP (2011 international-$). Production-based emissions are based on territorial emissions, which do not account for emissions embedded in traded goods.

co2_per_unit_energy - Annual total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured in kilograms per kilowatt-hour of primary energy consumption. Production-based emissions are based on territorial emissions, which do not account for emissions embedded in traded goods.

coal_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from coal, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

coal_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from coal, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

consumption_co2 - Annual consumption-based emissions of carbon dioxide (COâ‚‚), measured in million tonnes. Consumption-based emissions are national or regional emissions which have been adjusted for trade (i.e. territorial/production emissions minus emissions embedded in exports, plus emissions embedded in imports). If a country's consumption-based emissions are higher than its production emissions it is a net importer of carbon dioxide. Data has been converted by Our World in Data from million tonnes of carbon to million tonnes of COâ‚‚ using a conversion factor of 3.664.

consumption_co2_per_capita - Annual consumption-based emissions of carbon dioxide (COâ‚‚), measured in tonnes per person. Consumption-based emissions are national or regional emissions which have been adjusted for trade (i.e. territorial/production emissions minus emissions embedded in exports, plus emissions embedded in imports). If a country's consumption-based emissions are higher than its production emissions it is a net importer of carbon dioxide. Consumption-based COâ‚‚ emissions have been converted by Our World in Data from tonnes of carbon to tonnes of COâ‚‚ using a conversion factor of 3.664.

consumption_co2_per_gdp - Annual consumption-based emissions of carbon dioxide (COâ‚‚), measured in kilograms per dollar of GDP (2011 international-$). Consumption-based emissions are national or regional emissions which have been adjusted for trade (i.e. territorial/production emissions minus emissions embedded in exports, plus emissions embedded in imports). If a country's consumption-based emissions are higher than its production emissions it is a net importer of carbon dioxide. Consumption-based COâ‚‚ emissions have been converted by Our World in Data from tonnes of carbon to tonnes of COâ‚‚ using a conversion factor of 3.664.

cumulative_cement_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from cement since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_co2 - Total cumulative production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_co2_including_luc - Total cumulative production-based emissions of carbon dioxide (COâ‚‚), including land-use change, since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_coal_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from coal since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_flaring_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from flaring since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_gas_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from gas since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_luc_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from land-use change since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_oil_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from oil since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

cumulative_other_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from other industry sources since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

energy_per_capita - Primary energy consumption per capita, measured in kilowatt-hours per person per year.

energy_per_gdp - Primary energy consumption per unit of gross domestic product, measured in kilowatt-hours per international-$.

flaring_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from flaring, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

flaring_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from flaring, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

gas_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from gas, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

gas_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from gas, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

ghg_excluding_lucf_per_capita - Total greenhouse gas emissions excluding land-use change and forestry, measured in tonnes of carbon dioxide-equivalents per capita.

ghg_per_capita - Total greenhouse gas emissions including land-use change and forestry, measured in tonnes of carbon dioxide-equivalents per capita.

land_use_change_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from land-use change, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

land_use_change_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from land-use change, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

methane - Total methane emissions including land-use change and forestry, measured in million tonnes of carbon dioxide-equivalents.

methane_per_capita - Total methane emissions including land-use change and forestry, measured in tonnes of carbon dioxide-equivalents per capita.

nitrous_oxide - Total nitrous oxide emissions including land-use change and forestry, measured in million tonnes of carbon dioxide-equivalents.

nitrous_oxide_per_capita - Total nitrous oxide emissions including land-use change and forestry, measured in tonnes of carbon dioxide-equivalents per capita.

oil_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from oil, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

oil_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from oil, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

other_co2_per_capita - Annual production-based emissions of carbon dioxide (COâ‚‚) from other industry sources, measured in tonnes per person. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

other_industry_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from other industry sources, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods.

primary_energy_consumption - Primary energy consumption, measured in terawatt-hours per year.

share_global_cement_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from cement, measured as a percentage of global production-based emissions of COâ‚‚ from cement in the same year. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from cement has been calculated by Our World in Data using global COâ‚‚ emissions from cement provided in the Global Carbon Budget dataset.

share_global_co2 - Annual total production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, measured as a percentage of global production-based emissions of COâ‚‚ in the same year. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions has been calculated by Our World in Data using global COâ‚‚ emissions provided in the Global Carbon Budget dataset. Global emissions include all country emissions as well as emissions from international aviation and shipping.

share_global_co2_including_luc - Annual total production-based emissions of carbon dioxide (COâ‚‚), including land-use change, measured as a percentage of global total production-based emissions of COâ‚‚ in the same year. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions has been calculated by Our World in Data using global COâ‚‚ emissions provided in the Global Carbon Budget dataset. Global emissions include all country emissions as well as emissions from international aviation and shipping.

share_global_coal_co2 - Annual production-based emissions of carbon dioxide (COâ‚‚) from coal, measured as a percentage of global production-based emissions of COâ‚‚ from coal in the same year. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from coal has been calculated by Our World in Data using global COâ‚‚ emissions from coal provided in the Global Carbon Budget dataset.

share_global_cumulative_cement_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from cement since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from cement since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from cement has been calculated by Our World in Data using global COâ‚‚ emissions from cement provided in the Global Carbon Budget dataset.

share_global_cumulative_co2 - Total cumulative production-based emissions of carbon dioxide (COâ‚‚), excluding land-use change, since the first year of data availability, measured as a percentage of global total cumulative production-based emissions of COâ‚‚ since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions has been calculated by Our World in Data using global COâ‚‚ emissions provided in the Global Carbon Budget dataset. Global emissions include all country emissions as well as emissions from international aviation and shipping.

share_global_cumulative_co2_including_luc - Total cumulative production-based emissions of carbon dioxide (COâ‚‚), including land-use change, since the first year of data availability, measured as a percentage of global total cumulative production-based emissions of COâ‚‚ (including land-use change) since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions has been calculated by Our World in Data using global COâ‚‚ emissions provided in the Global Carbon Budget dataset. Global emissions include all country emissions as well as emissions from international aviation and shipping.

share_global_cumulative_coal_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from coal since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from coal since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from coal has been calculated by Our World in Data using global COâ‚‚ emissions from coal provided in the Global Carbon Budget dataset.

share_global_cumulative_flaring_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from flaring since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from flaring since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from flaring has been calculated by Our World in Data using global COâ‚‚ emissions from flaring provided in the Global Carbon Budget dataset.

share_global_cumulative_gas_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from gas since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from gas since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from gas has been calculated by Our World in Data using global COâ‚‚ emissions from gas provided in the Global Carbon Budget dataset.

share_global_cumulative_luc_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from land-use change since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from land-use chang since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions has been calculated by Our World in Data using global COâ‚‚ emissions provided in the Global Carbon Budget dataset.

share_global_cumulative_oil_co2 - Cumulative production-based emissions of carbon dioxide (COâ‚‚) from oil since the first year of data availability, measured as a percentage of global cumulative production-based emissions of COâ‚‚ from oil since the first year of data availability. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Each country's share of global COâ‚‚ emissions from oil has been calculated by Our World in Data using global COâ‚‚ emissions from oil provided in the Global Carbon Budget dataset. Global oil emissions include all country emissions as well as emissions from international aviation and shipping.


### Extract World Fossil Fuel Industry

In [36]:
world_ghg = ghg_factors[ghg_factors['country'] == 'World']

In [37]:
world_ghg = world_ghg[['country','year','cement_co2', 'coal_co2', 'gas_co2', 'oil_co2', 'flaring_co2', 'other_industry_co2']].reset_index()

In [38]:
world_ghg[world_ghg['year'] == 2017][['country','year','cement_co2', 'coal_co2', 'gas_co2', 'oil_co2', 'flaring_co2', 'other_industry_co2']]

,country,year,cement_co2,coal_co2,gas_co2,oil_co2,flaring_co2,other_industry_co2
267,World,2017,1507.923,14506.974,7144.928,12242.628,391.992,302.294

In [39]:
print('Total Emission (2017): ',(1507.923+14506.974+7144.928+12242.628+391.992+302.294) * 1_000_000)
# accuracy check with the Kurzgesagt video

Total Emission (2017):  36096739000.0

In [40]:
del world_ghg['index']

In [41]:
world_ghg = world_ghg.fillna(0)

In [42]:
world_ghg

,country,year,cement_co2,coal_co2,gas_co2,oil_co2,flaring_co2,other_industry_co2
0,World,1750,0.000,9.351,0.000,0.000,0.000,0.000
1,World,1751,0.000,9.351,0.000,0.000,0.000,0.000
2,World,1752,0.000,9.354,0.000,0.000,0.000,0.000
3,World,1753,0.000,9.354,0.000,0.000,0.000,0.000
4,World,1754,0.000,9.358,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...
267,World,2017,1507.923,14506.974,7144.928,12242.628,391.992,302.294
268,World,2018,1569.218,14746.831,7529.847,12266.017,412.116,302.479
269,World,2019,1617.507,14725.978,7647.528,12345.653,439.254,306.639
270,World,2020,1637.537,14174.564,7556.290,11191.809,407.584,296.302
271,World,2021,1672.592,14979.598,7921.830,11837.159,416.526,296.146

## Global Temperature Anomaly

In [43]:
global_temp = pd.read_csv('datasets/factors/climate-change.csv')

In [44]:
global_temp = global_temp[global_temp['Entity'] == 'World']

In [45]:
global_temp = global_temp[['Entity', 'Date', 'Temperature anomaly']].dropna().reset_index()

In [46]:
del global_temp['index']

In [47]:
global_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Entity               1718 non-null   object
 1   Date                 1718 non-null   object
 2   Temperature anomaly  1718 non-null   float64
dtypes: float64(1), object(2)
memory usage: 40.4+ KB

In [48]:
global_temp['Date'] = pd.to_datetime(global_temp['Date'])

In [49]:
global_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Entity               1718 non-null   object
 1   Date                 1718 non-null   datetime64[ns]
 2   Temperature anomaly  1718 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 40.4+ KB

In [50]:
global_temp['Year'] = global_temp['Date'].dt.year

In [51]:
global_temp = global_temp[['Entity', 'Year', 'Temperature anomaly']].groupby(['Entity','Year']).mean().reset_index()

In [52]:
global_temp

    Entity  Year  Temperature anomaly
0    World  1880            -0.166667
1    World  1881            -0.082500
2    World  1882            -0.110000
3    World  1883            -0.174167
4    World  1884            -0.280000
..     ...   ...                  ...
139  World  2019             0.976667
140  World  2020             1.017500
141  World  2021             0.844167
142  World  2022             0.891667
143  World  2023             0.915000

[144 rows x 3 columns]

# Exporting the Datasets

### Final touch before export, checking and making the column names uniform

Total greenhouse gas emission per country - annual basis

In [53]:
total_ghg_country = total_ghg_country.rename(columns = {'Entity' : 'Name', 'Code' : 'ISO', 'Annual greenhouse gas emissions': 'GHG Emissions'})

In [54]:
total_ghg_country

              Name  ISO  Year  GHG Emissions
0      Afghanistan  AFG  1851      7373214.5
1      Afghanistan  AFG  1852      7422393.5
2      Afghanistan  AFG  1853      7483595.5
3      Afghanistan  AFG  1854      7532321.0
4      Afghanistan  AFG  1855      7580708.5
...            ...  ...   ...            ...
35221     Zimbabwe  ZWE  2017     37999464.0
35222     Zimbabwe  ZWE  2018     39079344.0
35223     Zimbabwe  ZWE  2019     38701420.0
35224     Zimbabwe  ZWE  2020     37733230.0
35225     Zimbabwe  ZWE  2021     38060004.0

[34029 rows x 4 columns]

Greenhouse gas emission to population ratio per country - annual basis

In [55]:
perCapita_ghg_country.rename(columns = {'Entity' : 'Name', 'Code' : 'ISO', 'Annual greenhouse gas emissions': 'GHG Emissions per Capita'})

              Name  ISO  Year  Greenhouse gas emissions per person
0      Afghanistan  AFG  1851                             1.955849
1      Afghanistan  AFG  1852                             1.959601
2      Afghanistan  AFG  1853                             1.965935
3      Afghanistan  AFG  1854                             1.968897
4      Afghanistan  AFG  1855                             1.971694
...            ...  ...   ...                                  ...
33553     Zimbabwe  ZWE  2017                             2.576042
33554     Zimbabwe  ZWE  2018                             2.596256
33555     Zimbabwe  ZWE  2019                             2.520509
33556     Zimbabwe  ZWE  2020                             2.408044
33557     Zimbabwe  ZWE  2021                             2.379713

[33387 rows x 4 columns]

Weather related disaster displacement per country/territory - annual basis

In [56]:
world_related_dis = weather_related_dis.rename(columns = {'Country / Territory' : 'Name', 'ISO3' : 'ISO', 'Disaster Internal Displacements': 'Weather Related Displacements'})

In [57]:
world_related_dis

             Name  ISO  Year  Weather Related Displacements
0      Abyei Area  AB9  2018                              2
1      Abyei Area  AB9  2019                          40000
2     Afghanistan  AFG  2008                            180
3     Afghanistan  AFG  2009                          25000
4     Afghanistan  AFG  2010                          70000
...           ...  ...   ...                            ...
1451     Zimbabwe  ZWE  2017                          10308
1452     Zimbabwe  ZWE  2018                           1066
1453     Zimbabwe  ZWE  2019                          52400
1454     Zimbabwe  ZWE  2020                            385
1455     Zimbabwe  ZWE  2021                           2338

[1456 rows x 4 columns]

Fossil fuel industry and other industries emission in the world - annual basis

In [84]:
world_co2 = world_ghg.rename(columns = {'country' : 'Name', 'year' : 'Year', 'cement_co2': 'Cement CO2', 'coal_co2' : 'Coal CO2', 'gas_co2' : 'Gas CO2',
                           'oil_co2': 'Oil CO2', 'flaring_co2':'Flaring CO2', 'other_industry_co2': 'Other Industry CO2'})

In [85]:
world_co2

,Name,Year,Cement CO2,Coal CO2,Gas CO2,Oil CO2,Flaring CO2,Other Industry CO2
0,World,1750,0.000,9.351,0.000,0.000,0.000,0.000
1,World,1751,0.000,9.351,0.000,0.000,0.000,0.000
2,World,1752,0.000,9.354,0.000,0.000,0.000,0.000
3,World,1753,0.000,9.354,0.000,0.000,0.000,0.000
4,World,1754,0.000,9.358,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...
267,World,2017,1507.923,14506.974,7144.928,12242.628,391.992,302.294
268,World,2018,1569.218,14746.831,7529.847,12266.017,412.116,302.479
269,World,2019,1617.507,14725.978,7647.528,12345.653,439.254,306.639
270,World,2020,1637.537,14174.564,7556.290,11191.809,407.584,296.302
271,World,2021,1672.592,14979.598,7921.830,11837.159,416.526,296.146

Getting `world_co2` dataset ready for animated line chart

In [86]:
years = []
factors = []
values = []

for index, each in world_co2.iterrows():
    for each2 in ['Cement CO2','Coal CO2','Gas CO2','Oil CO2','Flaring CO2','Other Industry CO2']:
        years.append(each['Year'])
        factors.append(each2)
        values.append(each[each2]/1000)
        
for each in range(len(years)):
    print(years[each], factors[each], values[each])

1750 Cement CO2 0.0
1750 Coal CO2 0.009351000000000002
1750 Gas CO2 0.0
1750 Oil CO2 0.0
1750 Flaring CO2 0.0
1750 Other Industry CO2 0.0
1751 Cement CO2 0.0
1751 Coal CO2 0.009351000000000002
1751 Gas CO2 0.0
1751 Oil CO2 0.0
1751 Flaring CO2 0.0
1751 Other Industry CO2 0.0
1752 Cement CO2 0.0
1752 Coal CO2 0.009354
1752 Gas CO2 0.0
1752 Oil CO2 0.0
1752 Flaring CO2 0.0
1752 Other Industry CO2 0.0
1753 Cement CO2 0.0
1753 Coal CO2 0.009354
1753 Gas CO2 0.0
1753 Oil CO2 0.0
1753 Flaring CO2 0.0
1753 Other Industry CO2 0.0
1754 Cement CO2 0.0
1754 Coal CO2 0.009358
1754 Gas CO2 0.0
1754 Oil CO2 0.0
1754 Flaring CO2 0.0
1754 Other Industry CO2 0.0
1755 Cement CO2 0.0
1755 Coal CO2 0.009362
1755 Gas CO2 0.0
1755 Oil CO2 0.0
1755 Flaring CO2 0.0
1755 Other Industry CO2 0.0
1756 Cement CO2 0.0
1756 Coal CO2 0.010006000000000001
1756 Gas CO2 0.0
1756 Oil CO2 0.0
1756 Flaring CO2 0.0
1756 Other Industry CO2 0.0
1757 Cement CO2 0.0
1757 Coal CO2 0.01001
1757 Gas CO2 0.0
1757 Oil CO2 0.0
1757 Flaring CO2 0.0
1757 Other Industry CO2 0.0
1758 Cement CO2 0.0
1758 Coal CO2 0.010013999999999999
1758 Gas CO2 0.0
1758 Oil CO2 0.0
1758 Flaring CO2 0.0
1758 Other Industry CO2 0.0
1759 Cement CO2 0.0
1759 Coal CO2 0.010017
1759 Gas CO2 0.0
1759 Oil CO2 0.0
1759 Flaring CO2 0.0
1759 Other Industry CO2 0.0
1760 Cement CO2 0.0
1760 Coal CO2 0.010017
1760 Gas CO2 0.0
1760 Oil CO2 0.0
1760 Flaring CO2 0.0
1760 Other Industry CO2 0.0
1761 Cement CO2 0.0
1761 Coal CO2 0.010974
1761 Gas CO2 0.0
1761 Oil CO2 0.0
1761 Flaring CO2 0.0
1761 Other Industry CO2 0.0
1762 Cement CO2 0.0
1762 Coal CO2 0.010977
1762 Gas CO2 0.0
1762 Oil CO2 0.0
1762 Flaring CO2 0.0
1762 Other Industry CO2 0.0
1763 Cement CO2 0.0
1763 Coal CO2 0.010981
1763 Gas CO2 0.0
1763 Oil CO2 0.0
1763 Flaring CO2 0.0
1763 Other Industry CO2 0.0
1764 Cement CO2 0.0
1764 Coal CO2 0.010985
1764 Gas CO2 0.0
1764 Oil CO2 0.0
1764 Flaring CO2 0.0
1764 Other Industry CO2 0.0
1765 Cement CO2 0.0
1765 Coal CO2 0.010988
1765 Gas CO2 0.0
1765 Oil CO2 0.0
1765 Flaring CO2 0.0
1765 Other Industry CO2 0.0
1766 Cement CO2 0.0
1766 Coal CO2 0.01226
1766 Gas CO2 0.0
1766 Oil CO2 0.0
1766 Flaring CO2 0.0
1766 Other Industry CO2 0.0
1767 Cement CO2 0.0
1767 Coal CO2 0.012263
1767 Gas CO2 0.0
1767 Oil CO2 0.0
1767 Flaring CO2 0.0
1767 Other Industry CO2 0.0
1768 Cement CO2 0.0
1768 Coal CO2 0.012267
1768 Gas CO2 0.0
1768 Oil CO2 0.0
1768 Flaring CO2 0.0
1768 Other Industry CO2 0.0
1769 Cement CO2 0.0
1769 Coal CO2 0.012271
1769 Gas CO2 0.0
1769 Oil CO2 0.0
1769 Flaring CO2 0.0
1769 Other Industry CO2 0.0
1770 Cement CO2 0.0
1770 Coal CO2 0.012273999999999998
1770 Gas CO2 0.0
1770 Oil CO2 0.0
1770 Flaring CO2 0.0
1770 Other Industry CO2 0.0
1771 Cement CO2 0.0
1771 Coal CO2 0.013612
1771 Gas CO2 0.0
1771 Oil CO2 0.0
1771 Flaring CO2 0.0
1771 Other Industry CO2 0.0
1772 Cement CO2 0.0
1772 Coal CO2 0.013615
1772 Gas CO2 0.0
1772 Oil CO2 0.0
1772 Flaring CO2 0.0
1772 Other Industry CO2 0.0
1773 Cement CO2 0.0
1773 Coal CO2 0.013619
1773 Gas CO2 0.0
1773 Oil CO2 0.0
1773 Flaring CO2 0.0
1773 Other Industry CO2 0.0
1774 Cement CO2 0.0
1774 Coal CO2 0.013623
1774 Gas CO2 0.0
1774 Oil CO2 0.0
1774 Flaring CO2 0.0
1774 Other Industry CO2 0.0
1775 Cement CO2 0.0
1775 Coal CO2 0.013626
1775 Gas CO2 0.0
1775 Oil CO2 0.0
1775 Flaring CO2 0.0
1775 Other Industry CO2 0.0
1776 Cement CO2 0.0
1776 Coal CO2 0.015037
1776 Gas CO2 0.0
1776 Oil CO2 0.0
1776 Flaring CO2 0.0
1776 Other Industry CO2 0.0
1777 Cement CO2 0.0
1777 Coal CO2 0.015041
1777 Gas CO2 0.0
1777 Oil CO2 0.0
1777 Flaring CO2 0.0
1777 Other Industry CO2 0.0
1778 Cement CO2 0.0
1778 Coal CO2 0.015044
1778 Gas CO2 0.0
1778 Oil CO2 0.0
1778 Flaring CO2 0.0
1778 Other Industry CO2 0.0
1779 Cement CO2 0.0
1779 Coal CO2 0.015048
1779 Gas CO2 0.0
1779 Oil CO2 0.0
1779 Flaring CO2 0.0
1779 Other Industry CO2 0.0
1780 Cement CO2 0.0
1780 Coal CO2 0.015054999999999999
1780 Gas CO2 0.0
1780 Oil CO2 0.0
1780 Flaring CO2 0.0
1780 Other Industry CO2 0.0
1781 Cement CO2 0.0
1781 Coal CO2 0.016843
1781 Gas CO2 0.0
1781 Oil CO2 0.0
1781 Flaring CO2 0.0
1781 Other Industry CO2 0.0
1782 Cement CO2 0.0
1782 Coal CO2 0.016847
1782 Gas CO2 0.0
1782 Oil CO2 0.0
1782 Flaring CO2 0.0
1782 Other Industry CO2 0.0
1783 Cement CO2 0.0
1783 Coal CO2 0.016854
1783 Gas CO2 0.0
1783 Oil CO2 0.0
1783 Flaring CO2 0.0
1783 Other Industry CO2 0.0
1784 Cement CO2 0.0
1784 Coal CO2 0.016858
1784 Gas CO2 0.0
1784 Oil CO2 0.0
1784 Flaring CO2 0.0
1784 Other Industry CO2 0.0
1785 Cement CO2 0.0
1785 Coal CO2 0.016869
1785 Gas CO2 0.0
1785 Oil CO2 0.0
1785 Flaring CO2 0.0
1785 Other Industry CO2 0.0
1786 Cement CO2 0.0
1786 Coal CO2 0.019152000000000002
1786 Gas CO2 0.0
1786 Oil CO2 0.0
1786 Flaring CO2 0.0
1786 Other Industry CO2 0.0
1787 Cement CO2 0.0
1787 Coal CO2 0.019159
1787 Gas CO2 0.0
1787 Oil CO2 0.0
1787 Flaring CO2 0.0
1787 Other Industry CO2 0.0
1788 Cement CO2 0.0
1788 Coal CO2 0.019163
1788 Gas CO2 0.0
1788 Oil CO2 0.0
1788 Flaring CO2 0.0
1788 Other Industry CO2 0.0
1789 Cement CO2 0.0
1789 Coal CO2 0.019170000000000003
1789 Gas CO2 0.0
1789 Oil CO2 0.0
1789 Flaring CO2 0.0
1789 Other Industry CO2 0.0
1790 Cement CO2 0.0
1790 Coal CO2 0.019177
1790 Gas CO2 0.0
1790 Oil CO2 0.0
1790 Flaring CO2 0.0
1790 Other Industry CO2 0.0
1791 Cement CO2 0.0
1791 Coal CO2 0.02142
1791 Gas CO2 0.0
1791 Oil CO2 0.0
1791 Flaring CO2 0.0
1791 Other Industry CO2 0.0
1792 Cement CO2 0.0
1792 Coal CO2 0.021896000000000002
1792 Gas CO2 0.0
1792 Oil CO2 0.0
1792 Flaring CO2 0.0
1792 Other Industry CO2 0.0
1793 Cement CO2 0.0
1793 Coal CO2 0.021914000000000003
1793 Gas CO2 0.0
1793 Oil CO2 0.0
1793 Flaring CO2 0.0
1793 Other Industry CO2 0.0
1794 Cement CO2 0.0
1794 Coal CO2 0.021881
1794 Gas CO2 0.0
1794 Oil CO2 0.0
1794 Flaring CO2 0.0
1794 Other Industry CO2 0.0
1795 Cement CO2 0.0
1795 Coal CO2 0.021892
1795 Gas CO2 0.0
1795 Oil CO2 0.0
1795 Flaring CO2 0.0
1795 Other Industry CO2 0.0
1796 Cement CO2 0.0
1796 Coal CO2 0.022951
1796 Gas CO2 0.0
1796 Oil CO2 0.0
1796 Flaring CO2 0.0
1796 Other Industry CO2 0.0
1797 Cement CO2 0.0
1797 Coal CO2 0.024094
1797 Gas CO2 0.0
1797 Oil CO2 0.0
1797 Flaring CO2 0.0
1797 Other Industry CO2 0.0
1798 Cement CO2 0.0
1798 Coal CO2 0.025095
1798 Gas CO2 0.0
1798 Oil CO2 0.0
1798 Flaring CO2 0.0
1798 Other Industry CO2 0.0
1799 Cement CO2 0.0
1799 Coal CO2 0.026428
1799 Gas CO2 0.0
1799 Oil CO2 0.0
1799 Flaring CO2 0.0
1799 Other Industry CO2 0.0
1800 Cement CO2 0.0
1800 Coal CO2 0.028092
1800 Gas CO2 0.0
1800 Oil CO2 0.0
1800 Flaring CO2 0.0
1800 Other Industry CO2 0.0
1801 Cement CO2 0.0
1801 Coal CO2 0.027960000000000002
1801 Gas CO2 0.0
1801 Oil CO2 0.0
1801 Flaring CO2 0.0
1801 Other Industry CO2 0.0
1802 Cement CO2 0.0
1802 Coal CO2 0.036783
1802 Gas CO2 0.0
1802 Oil CO2 0.0
1802 Flaring CO2 0.0
1802 Other Industry CO2 0.0
1803 Cement CO2 0.0
1803 Coal CO2 0.031488
1803 Gas CO2 0.0
1803 Oil CO2 0.0
1803 Flaring CO2 0.0
1803 Other Industry CO2 0.0
1804 Cement CO2 0.0
1804 Coal CO2 0.03431
1804 Gas CO2 0.0
1804 Oil CO2 0.0
1804 Flaring CO2 0.0
1804 Other Industry CO2 0.0
1805 Cement CO2 0.0
1805 Coal CO2 0.033419
1805 Gas CO2 0.0
1805 Oil CO2 0.0
1805 Flaring CO2 0.0
1805 Other Industry CO2 0.0
1806 Cement CO2 0.0
1806 Coal CO2 0.035046
1806 Gas CO2 0.0
1806 Oil CO2 0.0
1806 Flaring CO2 0.0
1806 Other Industry CO2 0.0
1807 Cement CO2 0.0
1807 Coal CO2 0.036874000000000004
1807 Gas CO2 0.0
1807 Oil CO2 0.0
1807 Flaring CO2 0.0
1807 Other Industry CO2 0.0
1808 Cement CO2 0.0
1808 Coal CO2 0.035064
1808 Gas CO2 0.0
1808 Oil CO2 0.0
1808 Flaring CO2 0.0
1808 Other Industry CO2 0.0
1809 Cement CO2 0.0
1809 Coal CO2 0.03509
1809 Gas CO2 0.0
1809 Oil CO2 0.0
1809 Flaring CO2 0.0
1809 Other Industry CO2 0.0
1810 Cement CO2 0.0
1810 Coal CO2 0.037380000000000004
1810 Gas CO2 0.0
1810 Oil CO2 0.0
1810 Flaring CO2 0.0
1810 Other Industry CO2 0.0
1811 Cement CO2 0.0
1811 Coal CO2 0.039582
1811 Gas CO2 0.0
1811 Oil CO2 0.0
1811 Flaring CO2 0.0
1811 Other Industry CO2 0.0
1812 Cement CO2 0.0
1812 Coal CO2 0.041006999999999995
1812 Gas CO2 0.0
1812 Oil CO2 0.0
1812 Flaring CO2 0.0
1812 Other Industry CO2 0.0
1813 Cement CO2 0.0
1813 Coal CO2 0.04122
1813 Gas CO2 0.0
1813 Oil CO2 0.0
1813 Flaring CO2 0.0
1813 Other Industry CO2 0.0
1814 Cement CO2 0.0
1814 Coal CO2 0.042129
1814 Gas CO2 0.0
1814 Oil CO2 0.0
1814 Flaring CO2 0.0
1814 Other Industry CO2 0.0
1815 Cement CO2 0.0
1815 Coal CO2 0.043488
1815 Gas CO2 0.0
1815 Oil CO2 0.0
1815 Flaring CO2 0.0
1815 Other Industry CO2 0.0
1816 Cement CO2 0.0
1816 Coal CO2 0.047665
1816 Gas CO2 0.0
1816 Oil CO2 0.0
1816 Flaring CO2 0.0
1816 Other Industry CO2 0.0
1817 Cement CO2 0.0
1817 Coal CO2 0.049430999999999996
1817 Gas CO2 0.0
1817 Oil CO2 0.0
1817 Flaring CO2 0.0
1817 Other Industry CO2 0.0
1818 Cement CO2 0.0
1818 Coal CO2 0.049644
1818 Gas CO2 0.0
1818 Oil CO2 0.0
1818 Flaring CO2 0.0
1818 Other Industry CO2 0.0
1819 Cement CO2 0.0
1819 Coal CO2 0.049948
1819 Gas CO2 0.0
1819 Oil CO2 0.0
1819 Flaring CO2 0.0
1819 Other Industry CO2 0.0
1820 Cement CO2 0.0
1820 Coal CO2 0.050688000000000004
1820 Gas CO2 0.0
1820 Oil CO2 0.0
1820 Flaring CO2 0.0
1820 Other Industry CO2 0.0
1821 Cement CO2 0.0
1821 Coal CO2 0.051435
1821 Gas CO2 0.0
1821 Oil CO2 0.0
1821 Flaring CO2 0.0
1821 Other Industry CO2 0.0
1822 Cement CO2 0.0
1822 Coal CO2 0.053465000000000006
1822 Gas CO2 0.0
1822 Oil CO2 0.0
1822 Flaring CO2 0.0
1822 Other Industry CO2 0.0
1823 Cement CO2 0.0
1823 Coal CO2 0.056549999999999996
1823 Gas CO2 0.0
1823 Oil CO2 0.0
1823 Flaring CO2 0.0
1823 Other Industry CO2 0.0
1824 Cement CO2 0.0
1824 Coal CO2 0.058525
1824 Gas CO2 0.0
1824 Oil CO2 0.0
1824 Flaring CO2 0.0
1824 Other Industry CO2 0.0
1825 Cement CO2 0.0
1825 Coal CO2 0.060756
1825 Gas CO2 0.0
1825 Oil CO2 0.0
1825 Flaring CO2 0.0
1825 Other Industry CO2 0.0
1826 Cement CO2 0.0
1826 Coal CO2 0.06142
1826 Gas CO2 0.0
1826 Oil CO2 0.0
1826 Flaring CO2 0.0
1826 Other Industry CO2 0.0
1827 Cement CO2 0.0
1827 Coal CO2 0.065915
1827 Gas CO2 0.0
1827 Oil CO2 0.0
1827 Flaring CO2 0.0
1827 Other Industry CO2 0.0
1828 Cement CO2 0.0
1828 Coal CO2 0.066637
1828 Gas CO2 0.0
1828 Oil CO2 0.0
1828 Flaring CO2 0.0
1828 Other Industry CO2 0.0
1829 Cement CO2 0.0
1829 Coal CO2 0.066395
1829 Gas CO2 0.0
1829 Oil CO2 0.0
1829 Flaring CO2 0.0
1829 Other Industry CO2 0.0
1830 Cement CO2 0.0
1830 Coal CO2 0.08912300000000001
1830 Gas CO2 0.0
1830 Oil CO2 0.0
1830 Flaring CO2 0.0
1830 Other Industry CO2 0.0
1831 Cement CO2 0.0
1831 Coal CO2 0.084528
1831 Gas CO2 0.0
1831 Oil CO2 0.0
1831 Flaring CO2 0.0
1831 Other Industry CO2 0.0
1832 Cement CO2 0.0
1832 Coal CO2 0.085111
1832 Gas CO2 0.0
1832 Oil CO2 0.0
1832 Flaring CO2 0.0
1832 Other Industry CO2 0.0
1833 Cement CO2 0.0
1833 Coal CO2 0.086807
1833 Gas CO2 0.0
1833 Oil CO2 0.0
1833 Flaring CO2 0.0
1833 Other Industry CO2 0.0
1834 Cement CO2 0.0
1834 Coal CO2 0.08848600000000001
1834 Gas CO2 0.0
1834 Oil CO2 0.0
1834 Flaring CO2 0.0
1834 Other Industry CO2 0.0
1835 Cement CO2 0.0
1835 Coal CO2 0.090446
1835 Gas CO2 0.0
1835 Oil CO2 0.0
1835 Flaring CO2 0.0
1835 Other Industry CO2 0.0
1836 Cement CO2 0.0
1836 Coal CO2 0.104776
1836 Gas CO2 0.0
1836 Oil CO2 0.0
1836 Flaring CO2 0.0
1836 Other Industry CO2 0.0
1837 Cement CO2 0.0
1837 Coal CO2 0.104691
1837 Gas CO2 0.0
1837 Oil CO2 0.0
1837 Flaring CO2 0.0
1837 Other Industry CO2 0.0
1838 Cement CO2 0.0
1838 Coal CO2 0.108044
1838 Gas CO2 0.0
1838 Oil CO2 0.0
1838 Flaring CO2 0.0
1838 Other Industry CO2 0.0
1839 Cement CO2 0.0
1839 Coal CO2 0.111613
1839 Gas CO2 0.0
1839 Oil CO2 0.0
1839 Flaring CO2 0.0

1839 Other Industry CO2 0.0
1840 Cement CO2 0.0
1840 Coal CO2 0.11893000000000001
1840 Gas CO2 0.0
1840 Oil CO2 0.0
1840 Flaring CO2 0.0
1840 Other Industry CO2 0.0
1841 Cement CO2 0.0
1841 Coal CO2 0.122619
1841 Gas CO2 0.0
1841 Oil CO2 0.0
1841 Flaring CO2 0.0
1841 Other Industry CO2 0.0
1842 Cement CO2 0.0
1842 Coal CO2 0.12950399999999998
1842 Gas CO2 0.0
1842 Oil CO2 0.0
1842 Flaring CO2 0.0
1842 Other Industry CO2 0.0
1843 Cement CO2 0.0
1843 Coal CO2 0.132853
1843 Gas CO2 0.0
1843 Oil CO2 0.0
1843 Flaring CO2 0.0
1843 Other Industry CO2 0.0
1844 Cement CO2 0.0
1844 Coal CO2 0.141423
1844 Gas CO2 0.0
1844 Oil CO2 0.0
1844 Flaring CO2 0.0
1844 Other Industry CO2 0.0
1845 Cement CO2 0.0
1845 Coal CO2 0.15521100000000002
1845 Gas CO2 0.0
1845 Oil CO2 0.0
1845 Flaring CO2 0.0
1845 Other Industry CO2 0.0
1846 Cement CO2 0.0
1846 Coal CO2 0.15779400000000002
1846 Gas CO2 0.0
1846 Oil CO2 0.0
1846 Flaring CO2 0.0
1846 Other Industry CO2 0.0
1847 Cement CO2 0.0
1847 Coal CO2 0.172402
1847 Gas CO2 0.0
1847 Oil CO2 0.0
1847 Flaring CO2 0.0
1847 Other Industry CO2 0.0
1848 Cement CO2 0.0
1848 Coal CO2 0.173816
1848 Gas CO2 0.0
1848 Oil CO2 0.0
1848 Flaring CO2 0.0
1848 Other Industry CO2 0.0
1849 Cement CO2 0.0
1849 Coal CO2 0.183511
1849 Gas CO2 0.0
1849 Oil CO2 0.0
1849 Flaring CO2 0.0
1849 Other Industry CO2 0.0
1850 Cement CO2 0.0
1850 Coal CO2 0.196896
1850 Gas CO2 0.0
1850 Oil CO2 0.0
1850 Flaring CO2 0.0
1850 Other Industry CO2 0.0
1851 Cement CO2 0.0
1851 Coal CO2 0.198805
1851 Gas CO2 0.0
1851 Oil CO2 0.0
1851 Flaring CO2 0.0
1851 Other Industry CO2 0.0
1852 Cement CO2 0.0
1852 Coal CO2 0.20755099999999999
1852 Gas CO2 0.0
1852 Oil CO2 0.0
1852 Flaring CO2 0.0
1852 Other Industry CO2 0.0
1853 Cement CO2 0.0
1853 Coal CO2 0.217209
1853 Gas CO2 0.0
1853 Oil CO2 0.0
1853 Flaring CO2 0.0
1853 Other Industry CO2 0.0
1854 Cement CO2 0.0
1854 Coal CO2 0.255139
1854 Gas CO2 0.0
1854 Oil CO2 0.0
1854 Flaring CO2 0.0
1854 Other Industry CO2 0.0
1855 Cement CO2 0.0
1855 Coal CO2 0.260129
1855 Gas CO2 0.0
1855 Oil CO2 3.7e-05
1855 Flaring CO2 0.0
1855 Other Industry CO2 0.0
1856 Cement CO2 0.0
1856 Coal CO2 0.27725099999999997
1856 Gas CO2 0.0
1856 Oil CO2 4e-05
1856 Flaring CO2 0.0
1856 Other Industry CO2 0.0
1857 Cement CO2 0.0
1857 Coal CO2 0.27983800000000003
1857 Gas CO2 0.0
1857 Oil CO2 5.1e-05
1857 Flaring CO2 0.0
1857 Other Industry CO2 0.0
1858 Cement CO2 0.0
1858 Coal CO2 0.284109
1858 Gas CO2 0.0
1858 Oil CO2 6.2e-05
1858 Flaring CO2 0.0
1858 Other Industry CO2 0.0
1859 Cement CO2 0.0
1859 Coal CO2 0.301257
1859 Gas CO2 0.0
1859 Oil CO2 5.5e-05
1859 Flaring CO2 0.0
1859 Other Industry CO2 0.0
1860 Cement CO2 0.0
1860 Coal CO2 0.330368
1860 Gas CO2 0.0
1860 Oil CO2 0.000273
1860 Flaring CO2 0.0
1860 Other Industry CO2 0.0
1861 Cement CO2 0.0
1861 Coal CO2 0.346793
1861 Gas CO2 0.0
1861 Oil CO2 0.000941
1861 Flaring CO2 0.0
1861 Other Industry CO2 0.0
1862 Cement CO2 0.0
1862 Coal CO2 0.352658
1862 Gas CO2 0.0
1862 Oil CO2 0.001399
1862 Flaring CO2 0.0
1862 Other Industry CO2 0.0
1863 Cement CO2 0.0
1863 Coal CO2 0.37656599999999996
1863 Gas CO2 0.0
1863 Oil CO2 0.0012929999999999999
1863 Flaring CO2 0.0
1863 Other Industry CO2 0.0
1864 Cement CO2 0.0
1864 Coal CO2 0.40598
1864 Gas CO2 0.0
1864 Oil CO2 0.00111
1864 Flaring CO2 0.0
1864 Other Industry CO2 0.0
1865 Cement CO2 0.0
1865 Coal CO2 0.430987
1865 Gas CO2 0.0
1865 Oil CO2 0.00132
1865 Flaring CO2 0.0
1865 Other Industry CO2 0.0
1866 Cement CO2 0.0
1866 Coal CO2 0.44401799999999997
1866 Gas CO2 0.0
1866 Oil CO2 0.001952
1866 Flaring CO2 0.0
1866 Other Industry CO2 0.0
1867 Cement CO2 0.0
1867 Coal CO2 0.47583
1867 Gas CO2 0.0
1867 Oil CO2 0.0019850000000000002
1867 Flaring CO2 0.0
1867 Other Industry CO2 0.0
1868 Cement CO2 0.0
1868 Coal CO2 0.488464
1868 Gas CO2 0.0
1868 Oil CO2 0.0022890000000000002
1868 Flaring CO2 0.0
1868 Other Industry CO2 0.0
1869 Cement CO2 0.0
1869 Coal CO2 0.518516
1869 Gas CO2 0.0
1869 Oil CO2 0.002614
1869 Flaring CO2 0.0
1869 Other Industry CO2 0.0
1870 Cement CO2 0.0
1870 Coal CO2 0.529404
1870 Gas CO2 0.0
1870 Oil CO2 0.003133
1870 Flaring CO2 0.0
1870 Other Industry CO2 0.0
1871 Cement CO2 0.0
1871 Coal CO2 0.562861
1871 Gas CO2 0.0
1871 Oil CO2 0.003282
1871 Flaring CO2 0.0
1871 Other Industry CO2 0.0
1872 Cement CO2 0.0
1872 Coal CO2 0.622674
1872 Gas CO2 0.0
1872 Oil CO2 0.003698
1872 Flaring CO2 0.0
1872 Other Industry CO2 0.0
1873 Cement CO2 0.0
1873 Coal CO2 0.659749
1873 Gas CO2 0.0
1873 Oil CO2 0.00567
1873 Flaring CO2 0.0
1873 Other Industry CO2 0.0
1874 Cement CO2 0.0
1874 Coal CO2 0.616754
1874 Gas CO2 0.0
1874 Oil CO2 0.006243
1874 Flaring CO2 0.0
1874 Other Industry CO2 0.0
1875 Cement CO2 0.0
1875 Coal CO2 0.669964
1875 Gas CO2 0.0
1875 Oil CO2 0.005835
1875 Flaring CO2 0.0
1875 Other Industry CO2 0.0
1876 Cement CO2 0.0
1876 Coal CO2 0.6790170000000001
1876 Gas CO2 0.0
1876 Oil CO2 0.006535999999999999
1876 Flaring CO2 0.0
1876 Other Industry CO2 0.0
1877 Cement CO2 0.0
1877 Coal CO2 0.690274
1877 Gas CO2 0.0
1877 Oil CO2 0.008824
1877 Flaring CO2 0.0
1877 Other Industry CO2 0.0
1878 Cement CO2 0.0
1878 Coal CO2 0.694339
1878 Gas CO2 0.0
1878 Oil CO2 0.010041
1878 Flaring CO2 0.0
1878 Other Industry CO2 0.0
1879 Cement CO2 0.0
1879 Coal CO2 0.742208
1879 Gas CO2 0.0
1879 Oil CO2 0.01266
1879 Flaring CO2 0.0
1879 Other Industry CO2 0.0
1880 Cement CO2 0.0
1880 Coal CO2 0.8383400000000001
1880 Gas CO2 0.0
1880 Oil CO2 0.015364000000000001
1880 Flaring CO2 0.0
1880 Other Industry CO2 0.0
1881 Cement CO2 0.0
1881 Coal CO2 0.865162
1881 Gas CO2 0.0
1881 Oil CO2 0.017242
1881 Flaring CO2 0.0
1881 Other Industry CO2 0.0
1882 Cement CO2 0.0
1882 Coal CO2 0.912817
1882 Gas CO2 0.000165
1882 Oil CO2 0.018939
1882 Flaring CO2 0.0
1882 Other Industry CO2 0.0
1883 Cement CO2 0.0
1883 Coal CO2 0.974149
1883 Gas CO2 0.000381
1883 Oil CO2 0.016502
1883 Flaring CO2 0.0
1883 Other Industry CO2 0.0
1884 Cement CO2 0.0
1884 Coal CO2 0.982679
1884 Gas CO2 0.0011719999999999999
1884 Oil CO2 0.018323
1884 Flaring CO2 0.0
1884 Other Industry CO2 0.0
1885 Cement CO2 0.0
1885 Coal CO2 0.986996
1885 Gas CO2 0.003715
1885 Oil CO2 0.018959
1885 Flaring CO2 0.0
1885 Other Industry CO2 0.0
1886 Cement CO2 0.0
1886 Coal CO2 0.995975
1886 Gas CO2 0.0076760000000000005
1886 Oil CO2 0.021824000000000003
1886 Flaring CO2 0.0
1886 Other Industry CO2 0.0
1887 Cement CO2 1e-06
1887 Coal CO2 1.041488
1887 Gas CO2 0.011787
1887 Oil CO2 0.023482
1887 Flaring CO2 0.0
1887 Other Industry CO2 0.0
1888 Cement CO2 1e-06
1888 Coal CO2 1.150917
1888 Gas CO2 0.016774
1888 Oil CO2 0.024581
1888 Flaring CO2 0.0
1888 Other Industry CO2 0.0
1889 Cement CO2 1e-06
1889 Coal CO2 1.151165
1889 Gas CO2 0.012227
1889 Oil CO2 0.028407
1889 Flaring CO2 0.0
1889 Other Industry CO2 0.0
1890 Cement CO2 1e-06
1890 Coal CO2 1.2521179999999998
1890 Gas CO2 0.011688
1890 Oil CO2 0.034651
1890 Flaring CO2 0.0
1890 Other Industry CO2 0.0
1891 Cement CO2 1e-06
1891 Coal CO2 1.309094
1891 Gas CO2 0.008946999999999998
1891 Oil CO2 0.040832
1891 Flaring CO2 0.0
1891 Other Industry CO2 0.0
1892 Cement CO2 1e-06
1892 Coal CO2 1.322106
1892 Gas CO2 0.007775000000000001
1892 Oil CO2 0.040207
1892 Flaring CO2 0.0
1892 Other Industry CO2 0.0
1893 Cement CO2 1e-06
1893 Coal CO2 1.303833
1893 Gas CO2 0.007288
1893 Oil CO2 0.042546999999999995
1893 Flaring CO2 0.0
1893 Other Industry CO2 0.0
1894 Cement CO2 1e-06
1894 Coal CO2 1.3524580000000002
1894 Gas CO2 0.006698000000000001
1894 Oil CO2 0.041701999999999996
1894 Flaring CO2 0.0
1894 Other Industry CO2 0.0
1895 Cement CO2 1e-06
1895 Coal CO2 1.429691
1895 Gas CO2 0.007042
1895 Oil CO2 0.048539
1895 Flaring CO2 0.0
1895 Other Industry CO2 0.0
1896 Cement CO2 1e-06
1896 Coal CO2 1.474281
1896 Gas CO2 0.006848
1896 Oil CO2 0.052571
1896 Flaring CO2 0.0
1896 Other Industry CO2 0.0
1897 Cement CO2 1e-06
1897 Coal CO2 1.543481
1897 Gas CO2 0.007288
1897 Oil CO2 0.055531
1897 Flaring CO2 0.0
1897 Other Industry CO2 0.0
1898 Cement CO2 1e-06
1898 Coal CO2 1.628632
1898 Gas CO2 0.00846
1898 Oil CO2 0.057173
1898 Flaring CO2 0.0
1898 Other Industry CO2 0.0
1899 Cement CO2 1e-06
1899 Coal CO2 1.77986
1899 Gas CO2 0.010904
1899 Oil CO2 0.060031999999999995
1899 Flaring CO2 0.0
1899 Other Industry CO2 0.0
1900 Cement CO2 1e-06
1900 Coal CO2 1.873357
1900 Gas CO2 0.011542
1900 Oil CO2 0.06731000000000001
1900 Flaring CO2 0.0
1900 Other Industry CO2 0.0
1901 Cement CO2 2e-06
1901 Coal CO2 1.929132
1901 Gas CO2 0.012861000000000001
1901 Oil CO2 0.07475
1901 Flaring CO2 0.0
1901 Other Industry CO2 0.0
1902 Cement CO2 2e-06
1902 Coal CO2 1.973178
1902 Gas CO2 0.013696
1902 Oil CO2 0.080808
1902 Flaring CO2 0.0
1902 Other Industry CO2 0.0
1903 Cement CO2 3e-06
1903 Coal CO2 2.1540030000000003
1903 Gas CO2 0.014528000000000001
1903 Oil CO2 0.085562
1903 Flaring CO2 0.0
1903 Other Industry CO2 0.0
1904 Cement CO2 3e-06
1904 Coal CO2 2.1666640000000004
1904 Gas CO2 0.015165
1904 Oil CO2 0.096083
1904 Flaring CO2 0.0
1904 Other Industry CO2 0.0018340000000000001
1905 Cement CO2 4e-06
1905 Coal CO2 2.311143
1905 Gas CO2 0.01717
1905 Oil CO2 0.09701699999999999
1905 Flaring CO2 0.0
1905 Other Industry CO2 0.00198
1906 Cement CO2 4e-06
1906 Coal CO2 2.415683
1906 Gas CO2 0.019027000000000002
1906 Oil CO2 0.097893
1906 Flaring CO2 0.0
1906 Other Industry CO2 0.002127
1907 Cement CO2 5e-06
1907 Coal CO2 2.746956
1907 Gas CO2 0.019877
1907 Oil CO2 0.119416
1907 Flaring CO2 0.0
1907 Other Industry CO2 0.002054
1908 Cement CO2 0.000115
1908 Coal CO2 2.62602
1908 Gas CO2 0.019676
1908 Oil CO2 0.12875899999999998
1908 Flaring CO2 0.0
1908 Other Industry CO2 0.0018340000000000001
1909 Cement CO2 0.000116
1909 Coal CO2 2.730134
1909 Gas CO2 0.023523
1909 Oil CO2 0.134349
1909 Flaring CO2 0.0
1909 Other Industry CO2 0.002347
1910 Cement CO2 0.000135
1910 Coal CO2 2.862583
1910 Gas CO2 0.024915
1910 Oil CO2 0.143839
1910 Flaring CO2 0.0
1910 Other Industry CO2 0.002347
1911 Cement CO2 0.000148
1911 Coal CO2 2.898529
1911 Gas CO2 0.025718
1911 Oil CO2 0.152546
1911 Flaring CO2 0.0
1911 Other Industry CO2 0.002274
1912 Cement CO2 0.000177
1912 Coal CO2 3.04794
1912 Gas CO2 0.028315
1912 Oil CO2 0.15675899999999998
1912 Flaring CO2 0.0
1912 Other Industry CO2 0.002347
1913 Cement CO2 0.000203
1913 Coal CO2 3.2920700000000003
1913 Gas CO2 0.029598
1913 Oil CO2 0.181575
1913 Flaring CO2 0.0
1913 Other Industry CO2 0.002421
1914 Cement CO2 0.000147
1914 Coal CO2 2.961773
1914 Gas CO2 0.030136
1914 Oil CO2 0.185583
1914 Flaring CO2 0.0
1914 Other Industry CO2 0.002274
1915 Cement CO2 0.00016
1915 Coal CO2 2.9028270000000003
1915 Gas CO2 0.031866
1915 Oil CO2 0.197104
1915 Flaring CO2 0.0
1915 Other Industry CO2 0.002421
1916 Cement CO2 0.00018099999999999998
1916 Coal CO2 3.129373
1916 Gas CO2 0.038377
1916 Oil CO2 0.21463200000000002
1916 Flaring CO2 0.0

1916 Other Industry CO2 0.002714
1917 Cement CO2 0.000148
1917 Coal CO2 3.257893
1917 Gas CO2 0.040509
1917 Oil CO2 0.238808
1917 Flaring CO2 0.0
1917 Other Industry CO2 0.002494
1918 Cement CO2 0.00011999999999999999
1918 Coal CO2 3.209469
1918 Gas CO2 0.036518999999999996
1918 Oil CO2 0.244605
1918 Flaring CO2 0.0
1918 Other Industry CO2 0.002127
1919 Cement CO2 0.000125
1919 Coal CO2 2.715321
1919 Gas CO2 0.037948
1919 Oil CO2 0.272966
1919 Flaring CO2 0.0
1919 Other Industry CO2 0.0022010000000000003
1920 Cement CO2 0.000149
1920 Coal CO2 3.1259270000000003
1920 Gas CO2 0.041685
1920 Oil CO2 0.350954
1920 Flaring CO2 0.0
1920 Other Industry CO2 0.002347
1921 Cement CO2 0.00013000000000000002
1921 Coal CO2 2.668397
1921 Gas CO2 0.034991999999999995
1921 Oil CO2 0.384258
1921 Flaring CO2 0.0
1921 Other Industry CO2 0.0016870000000000001
1922 Cement CO2 0.000193
1922 Coal CO2 2.77067
1922 Gas CO2 0.040107
1922 Oil CO2 0.42634500000000003
1922 Flaring CO2 0.0
1922 Other Industry CO2 0.002421
1923 Cement CO2 0.000208
1923 Coal CO2 3.146423
1923 Gas CO2 0.052526
1923 Oil CO2 0.473527
1923 Flaring CO2 0.0
1923 Other Industry CO2 0.002714
1924 Cement CO2 0.000216
1924 Coal CO2 3.152649
1924 Gas CO2 0.059709000000000005
1924 Oil CO2 0.470812
1924 Flaring CO2 0.0
1924 Other Industry CO2 0.002714
1925 Cement CO2 0.014429
1925 Coal CO2 3.151418
1925 Gas CO2 0.06392199999999999
1925 Oil CO2 0.492787
1925 Flaring CO2 0.0
1925 Other Industry CO2 0.003081
1926 Cement CO2 0.01474
1926 Coal CO2 3.081757
1926 Gas CO2 0.06914400000000001
1926 Oil CO2 0.49064800000000003
1926 Flaring CO2 0.0
1926 Other Industry CO2 0.003007
1927 Cement CO2 0.015448
1927 Coal CO2 3.361539
1927 Gas CO2 0.076017
1927 Oil CO2 0.5378160000000001
1927 Flaring CO2 0.0
1927 Other Industry CO2 0.002934
1928 Cement CO2 0.035616
1928 Coal CO2 3.3053589999999997
1928 Gas CO2 0.082623
1928 Oil CO2 0.549539
1928 Flaring CO2 0.0
1928 Other Industry CO2 0.002934
1929 Cement CO2 0.036872999999999996
1929 Coal CO2 3.5222510000000002
1929 Gas CO2 0.102894
1929 Oil CO2 0.602778
1929 Flaring CO2 0.0
1929 Other Industry CO2 0.0028610000000000003
1930 Cement CO2 0.035561
1930 Coal CO2 3.214073
1930 Gas CO2 0.104224
1930 Oil CO2 0.578598
1930 Flaring CO2 0.0
1930 Other Industry CO2 0.002274
1931 Cement CO2 0.030931
1931 Coal CO2 2.83054
1931 Gas CO2 0.092887
1931 Oil CO2 0.560749
1931 Flaring CO2 0.0
1931 Other Industry CO2 0.0018340000000000001
1932 Cement CO2 0.024721
1932 Coal CO2 2.519949
1932 Gas CO2 0.088218
1932 Oil CO2 0.536592
1932 Flaring CO2 0.0
1932 Other Industry CO2 0.00132
1933 Cement CO2 0.023866
1933 Coal CO2 2.635637
1933 Gas CO2 0.090917
1933 Oil CO2 0.586389
1933 Flaring CO2 0.0
1933 Other Industry CO2 0.0015400000000000001
1934 Cement CO2 0.028542
1934 Coal CO2 2.878248
1934 Gas CO2 0.101949
1934 Oil CO2 0.620413
1934 Flaring CO2 0.0
1934 Other Industry CO2 0.0016140000000000002
1935 Cement CO2 0.03209
1935 Coal CO2 2.9968850000000002
1935 Gas CO2 0.111372
1935 Oil CO2 0.668785
1935 Flaring CO2 0.0
1935 Other Industry CO2 0.00198
1936 Cement CO2 0.038763
1936 Coal CO2 3.285172
1936 Gas CO2 0.125529
1936 Oil CO2 0.729131
1936 Flaring CO2 0.0
1936 Other Industry CO2 0.002494
1937 Cement CO2 0.040829
1937 Coal CO2 3.463736
1937 Gas CO2 0.140574
1937 Oil CO2 0.8215159999999999
1937 Flaring CO2 0.0
1937 Other Industry CO2 0.002714
1938 Cement CO2 0.038551
1938 Coal CO2 3.228046
1938 Gas CO2 0.135493
1938 Oil CO2 0.7969890000000001
1938 Flaring CO2 0.0
1938 Other Industry CO2 0.0022010000000000003
1939 Cement CO2 0.035686999999999997
1939 Coal CO2 3.435326
1939 Gas CO2 0.141328
1939 Oil CO2 0.830241
1939 Flaring CO2 0.0
1939 Other Industry CO2 0.0028610000000000003
1940 Cement CO2 0.031431
1940 Coal CO2 3.7940169999999998
1940 Gas CO2 0.15351499999999998
1940 Oil CO2 0.872467
1940 Flaring CO2 0.0
1940 Other Industry CO2 0.003227
1941 Cement CO2 0.043293
1941 Coal CO2 3.884161
1941 Gas CO2 0.153463
1941 Oil CO2 0.880697
1941 Flaring CO2 0.0
1941 Other Industry CO2 0.004033999999999999
1942 Cement CO2 0.038376
1942 Coal CO2 3.909448
1942 Gas CO2 0.166049
1942 Oil CO2 0.835716
1942 Flaring CO2 0.0
1942 Other Industry CO2 0.004033999999999999
1943 Cement CO2 0.03481
1943 Coal CO2 3.9250390000000004
1943 Gas CO2 0.1829
1943 Oil CO2 0.8880009999999999
1943 Flaring CO2 0.0
1943 Other Industry CO2 0.004328
1944 Cement CO2 0.022664
1944 Coal CO2 3.867923
1944 Gas CO2 0.197601
1944 Oil CO2 1.018141
1944 Flaring CO2 0.0
1944 Other Industry CO2 0.004328
1945 Cement CO2 0.022991
1945 Coal CO2 2.9982699999999998
1945 Gas CO2 0.216697
1945 Oil CO2 1.008345
1945 Flaring CO2 0.0
1945 Other Industry CO2 0.003961
1946 Cement CO2 0.03633
1946 Coal CO2 3.234314
1946 Gas CO2 0.223834
1946 Oil CO2 1.139899
1946 Flaring CO2 0.0
1946 Other Industry CO2 0.003961
1947 Cement CO2 0.043192
1947 Coal CO2 3.6215479999999998
1947 Gas CO2 0.247888
1947 Oil CO2 1.221313
1947 Flaring CO2 0.0
1947 Other Industry CO2 0.004548
1948 Cement CO2 0.051684
1948 Coal CO2 3.739455
1948 Gas CO2 0.28012200000000004
1948 Oil CO2 1.339607
1948 Flaring CO2 0.0
1948 Other Industry CO2 0.004841
1949 Cement CO2 0.058264
1949 Coal CO2 3.54631
1949 Gas CO2 0.300454
1949 Oil CO2 1.336641
1949 Flaring CO2 0.0
1949 Other Industry CO2 0.004181
1950 Cement CO2 0.066979
1950 Coal CO2 3.856215
1950 Gas CO2 0.353156
1950 Oil CO2 1.64831
1950 Flaring CO2 0.073624
1950 Other Industry CO2 0.004988
1951 Cement CO2 0.075839
1951 Coal CO2 4.06004
1951 Gas CO2 0.416186
1951 Oil CO2 1.742354
1951 Flaring CO2 0.079875
1951 Other Industry CO2 0.005501000000000001
1952 Cement CO2 0.080841
1952 Coal CO2 4.009059000000001
1952 Gas CO2 0.44708499999999995
1952 Oil CO2 1.8380239999999999
1952 Flaring CO2 0.08536400000000001
1952 Other Industry CO2 0.005355
1953 Cement CO2 0.089628
1953 Coal CO2 4.043705
1953 Gas CO2 0.474527
1953 Oil CO2 1.9521
1953 Flaring CO2 0.081348
1953 Other Industry CO2 0.006455
1954 Cement CO2 0.097231
1954 Coal CO2 4.039512
1954 Gas CO2 0.5013500000000001
1954 Oil CO2 2.068543
1954 Flaring CO2 0.077612
1954 Other Industry CO2 0.005721
1955 Cement CO2 0.10756600000000001
1955 Coal CO2 4.372781
1955 Gas CO2 0.5472290000000001
1955 Oil CO2 2.311864
1955 Flaring CO2 0.096836
1955 Other Industry CO2 0.006968
1956 Cement CO2 0.11662399999999999
1956 Coal CO2 4.597137
1956 Gas CO2 0.587229
1956 Oil CO2 2.5080479999999996
1956 Flaring CO2 0.108174
1956 Other Industry CO2 0.007042
1957 Cement CO2 0.12261
1957 Coal CO2 4.681798
1957 Gas CO2 0.6466660000000001
1957 Oil CO2 2.621266
1957 Flaring CO2 0.106386
1957 Other Industry CO2 0.006822
1958 Cement CO2 0.129775
1958 Coal CO2 4.754382
1958 Gas CO2 0.705825
1958 Oil CO2 2.726365
1958 Flaring CO2 0.09511499999999999
1958 Other Industry CO2 0.006161
1959 Cement CO2 0.14533600000000002
1959 Coal CO2 4.948027
1959 Gas CO2 0.758226
1959 Oil CO2 2.904649
1959 Flaring CO2 0.091694
1959 Other Industry CO2 0.008289
1960 Cement CO2 0.157493
1960 Coal CO2 5.152558
1960 Gas CO2 0.834527
1960 Oil CO2 3.126444
1960 Flaring CO2 0.08914
1960 Other Industry CO2 0.027507
1961 Cement CO2 0.164229
1961 Coal CO2 4.943283999999999
1961 Gas CO2 0.882007
1961 Oil CO2 3.3135030000000003
1961 Flaring CO2 0.086218
1961 Other Industry CO2 0.029219000000000002
1962 Cement CO2 0.17644300000000002
1962 Coal CO2 4.9287849999999995
1962 Gas CO2 0.967683
1962 Oil CO2 3.56194
1962 Flaring CO2 0.085931
1962 Other Industry CO2 0.030277000000000002
1963 Cement CO2 0.18606
1963 Coal CO2 5.109542
1963 Gas CO2 1.046822
1963 Oil CO2 3.806973
1963 Flaring CO2 0.090506
1963 Other Industry CO2 0.031751
1964 Cement CO2 0.20622
1964 Coal CO2 5.21519
1964 Gas CO2 1.15286
1964 Oil CO2 4.107569000000001
1964 Flaring CO2 0.112792
1964 Other Industry CO2 0.03498
1965 Cement CO2 0.21649000000000002
1965 Coal CO2 5.2932179999999995
1965 Gas CO2 1.230538
1965 Oil CO2 4.412375
1965 Flaring CO2 0.130443
1965 Other Industry CO2 0.03453199999999999
1966 Cement CO2 0.233053
1966 Coal CO2 5.351301
1966 Gas CO2 1.339839
1966 Oil CO2 4.761953
1966 Flaring CO2 0.144566
1966 Other Industry CO2 0.036220999999999996
1967 Cement CO2 0.23990799999999998
1967 Coal CO2 5.266113000000001
1967 Gas CO2 1.4329459999999998
1967 Oil CO2 5.07708
1967 Flaring CO2 0.19078299999999998
1967 Other Industry CO2 0.037200000000000004
1968 Cement CO2 0.255398
1968 Coal CO2 5.323236
1968 Gas CO2 1.5595709999999998
1968 Oil CO2 5.530292
1968 Flaring CO2 0.2038
1968 Other Industry CO2 0.038593
1969 Cement CO2 0.270791
1969 Coal CO2 5.521839
1969 Gas CO2 1.708518
1969 Oil CO2 5.980509
1969 Flaring CO2 0.244035
1969 Other Industry CO2 0.041707999999999995
1970 Cement CO2 0.28841100000000003
1970 Coal CO2 5.696270999999999
1970 Gas CO2 1.7906790000000001
1970 Oil CO2 6.801259
1970 Flaring CO2 0.277745
1970 Other Industry CO2 0.04435
1971 Cement CO2 0.30334500000000003
1971 Coal CO2 5.699823
1971 Gas CO2 1.933313
1971 Oil CO2 7.202926000000001
1971 Flaring CO2 0.321427
1971 Other Industry CO2 0.044661
1972 Cement CO2 0.321547
1972 Coal CO2 5.693585
1972 Gas CO2 2.052041
1972 Oil CO2 7.766614
1972 Flaring CO2 0.34687
1972 Other Industry CO2 0.048072000000000004
1973 Cement CO2 0.340512
1973 Coal CO2 5.862085
1973 Gas CO2 2.20389
1973 Oil CO2 8.225938
1973 Flaring CO2 0.402142
1973 Other Industry CO2 0.051627
1974 Cement CO2 0.34103300000000003
1974 Coal CO2 5.865810000000001
1974 Gas CO2 2.2589989999999998
1974 Oil CO2 8.107899
1974 Flaring CO2 0.391347
1974 Other Industry CO2 0.052388
1975 Cement CO2 0.339117
1975 Coal CO2 6.037091
1975 Gas CO2 2.2555430000000003
1975 Oil CO2 8.039023
1975 Flaring CO2 0.336685
1975 Other Industry CO2 0.047168999999999996
1976 Cement CO2 0.354146
1976 Coal CO2 6.263989
1976 Gas CO2 2.38685
1976 Oil CO2 8.541493000000001
1976 Flaring CO2 0.395391
1976 Other Industry CO2 0.050017000000000006
1977 Cement CO2 0.370868
1977 Coal CO2 6.417698000000001
1977 Gas CO2 2.441085
1977 Oil CO2 8.84206
1977 Flaring CO2 0.381443
1977 Other Industry CO2 0.049692
1978 Cement CO2 0.394692
1978 Coal CO2 6.531792
1978 Gas CO2 2.5503460000000002
1978 Oil CO2 9.159137000000001
1978 Flaring CO2 0.39015
1978 Other Industry CO2 0.051076
1979 Cement CO2 0.399877
1979 Coal CO2 6.840287
1979 Gas CO2 2.6889969999999996
1979 Oil CO2 9.276707
1979 Flaring CO2 0.36013
1979 Other Industry CO2 0.052464
1980 Cement CO2 0.40262
1980 Coal CO2 7.024129
1980 Gas CO2 2.758101
1980 Oil CO2 8.951775
1980 Flaring CO2 0.316436
1980 Other Industry CO2 0.048201999999999995
1981 Cement CO2 0.402748
1981 Coal CO2 7.0048829999999995
1981 Gas CO2 2.794347
1981 Oil CO2 8.550305
1981 Flaring CO2 0.237163
1981 Other Industry CO2 0.046672
1982 Cement CO2 0.400937
1982 Coal CO2 7.126512
1982 Gas CO2 2.7312730000000003
1982 Oil CO2 8.345175999999999
1982 Flaring CO2 0.23557499999999998
1982 Other Industry CO2 0.045013
1983 Cement CO2 0.409877
1983 Coal CO2 7.31419
1983 Gas CO2 2.760542
1983 Oil CO2 8.260815000000001
1983 Flaring CO2 0.212847
1983 Other Industry CO2 0.048269
1984 Cement CO2 0.417703
1984 Coal CO2 7.668797
1984 Gas CO2 3.010426
1984 Oil CO2 8.328841
1984 Flaring CO2 0.186751
1984 Other Industry CO2 0.052236
1985 Cement CO2 0.422772
1985 Coal CO2 8.217823000000001
1985 Gas CO2 3.1214009999999996
1985 Oil CO2 8.326771
1985 Flaring CO2 0.181447
1985 Other Industry CO2 0.055272
1986 Cement CO2 0.440349
1986 Coal CO2 8.335814000000001
1986 Gas CO2 3.045544
1986 Oil CO2 8.576334000000001
1986 Flaring CO2 0.169668
1986 Other Industry CO2 0.059649
1987 Cement CO2 0.459192
1987 Coal CO2 8.617361
1987 Gas CO2 3.30528
1987 Oil CO2 8.654658999999999
1987 Flaring CO2 0.163007
1987 Other Industry CO2 0.074406
1988 Cement CO2 0.48360899999999996
1988 Coal CO2 8.910819
1988 Gas CO2 3.4660219999999997
1988 Oil CO2 8.972672000000001
1988 Flaring CO2 0.18550899999999998
1988 Other Industry CO2 0.08916299999999999
1989 Cement CO2 0.4935
1989 Coal CO2 8.909616
1989 Gas CO2 3.639817
1989 Oil CO2 9.13008
1989 Flaring CO2 0.15068
1989 Other Industry CO2 0.08670900000000001
1990 Cement CO2 0.49385399999999996
1990 Coal CO2 8.688659
1990 Gas CO2 3.8331329999999997
1990 Oil CO2 9.249362
1990 Flaring CO2 0.26785899999999996
1990 Other Industry CO2 0.22461099999999998
1991 Cement CO2 0.507751
1991 Coal CO2 8.604035
1991 Gas CO2 3.9096770000000003
1991 Oil CO2 9.72343
1991 Flaring CO2 0.28296499999999997
1991 Other Industry CO2 0.216948
1992 Cement CO2 0.528942
1992 Coal CO2 8.399007
1992 Gas CO2 3.95812
1992 Oil CO2 9.226139
1992 Flaring CO2 0.250482
1992 Other Industry CO2 0.217334
1993 Cement CO2 0.5515119999999999
1993 Coal CO2 8.500946
1993 Gas CO2 4.067061
1993 Oil CO2 9.232772
1993 Flaring CO2 0.24405600000000002
1993 Other Industry CO2 0.216552
1994 Cement CO2 0.588461
1994 Coal CO2 8.548629
1994 Gas CO2 4.1020829999999995
1994 Oil CO2 9.265657
1994 Flaring CO2 0.248054
1994 Other Industry CO2 0.216615
1995 Cement CO2 0.622443
1995 Coal CO2 8.793981
1995 Gas CO2 4.209968
1995 Oil CO2 9.363845999999999
1995 Flaring CO2 0.244935
1995 Other Industry CO2 0.22354
1996 Cement CO2 0.635312
1996 Coal CO2 9.015794
1996 Gas CO2 4.395992000000001
1996 Oil CO2 9.643209
1996 Flaring CO2 0.247175
1996 Other Industry CO2 0.22190100000000001
1997 Cement CO2 0.6612319999999999
1997 Coal CO2 8.967540000000001
1997 Gas CO2 4.412478
1997 Oil CO2 9.78686
1997 Flaring CO2 0.250794
1997 Other Industry CO2 0.223678
1998 Cement CO2 0.658611
1998 Coal CO2 8.725984
1998 Gas CO2 4.484475000000001
1998 Oil CO2 9.883467000000001
1998 Flaring CO2 0.24025200000000002
1998 Other Industry CO2 0.22047
1999 Cement CO2 0.69101
1999 Coal CO2 8.855188
1999 Gas CO2 4.621802
1999 Oil CO2 10.112427
1999 Flaring CO2 0.23274799999999998
1999 Other Industry CO2 0.219213
2000 Cement CO2 0.721927
2000 Coal CO2 9.203117
2000 Gas CO2 4.731291000000001
2000 Oil CO2 10.302091
2000 Flaring CO2 0.278928
2000 Other Industry CO2 0.216267
2001 Cement CO2 0.754332
2001 Coal CO2 9.255257
2001 Gas CO2 4.773585
2001 Oil CO2 10.390668999999999
2001 Flaring CO2 0.281128
2001 Other Industry CO2 0.213078
2002 Cement CO2 0.796052
2002 Coal CO2 9.678959
2002 Gas CO2 4.905854000000001
2002 Oil CO2 10.385864
2002 Flaring CO2 0.298554
2002 Other Industry CO2 0.215754
2003 Cement CO2 0.852253
2003 Coal CO2 10.518464
2003 Gas CO2 5.081468
2003 Oil CO2 10.679654000000001
2003 Flaring CO2 0.299376
2003 Other Industry CO2 0.220382
2004 Cement CO2 0.910566
2004 Coal CO2 10.871584
2004 Gas CO2 5.25719
2004 Oil CO2 11.042504999999998
2004 Flaring CO2 0.323803
2004 Other Industry CO2 0.231047
2005 Cement CO2 0.964306
2005 Coal CO2 11.543334999999999
2005 Gas CO2 5.380666
2005 Oil CO2 11.139399
2005 Flaring CO2 0.345094
2005 Other Industry CO2 0.241802
2006 Cement CO2 1.0516690000000002
2006 Coal CO2 12.18884
2006 Gas CO2 5.5068090000000005
2006 Oil CO2 11.246321
2006 Flaring CO2 0.34686
2006 Other Industry CO2 0.252617
2007 Cement CO2 1.129389
2007 Coal CO2 12.77636
2007 Gas CO2 5.694134
2007 Oil CO2 11.283665000000001
2007 Flaring CO2 0.363985
2007 Other Industry CO2 0.259255
2008 Cement CO2 1.1437380000000001
2008 Coal CO2 13.192797
2008 Gas CO2 5.864291000000001
2008 Oil CO2 11.251325000000001
2008 Flaring CO2 0.374074
2008 Other Industry CO2 0.259611
2009 Cement CO2 1.17573
2009 Coal CO2 13.016428
2009 Gas CO2 5.751954
2009 Oil CO2 10.996948
2009 Flaring CO2 0.37940199999999996
2009 Other Industry CO2 0.243568
2010 Cement CO2 1.254878
2010 Coal CO2 13.926620999999999
2010 Gas CO2 6.195344
2010 Oil CO2 11.359883
2010 Flaring CO2 0.38165
2010 Other Industry CO2 0.245971
2011 Cement CO2 1.3497999999999999
2011 Coal CO2 14.737126
2011 Gas CO2 6.366902
2011 Oil CO2 11.388086
2011 Flaring CO2 0.37028
2011 Other Industry CO2 0.27481900000000004
2012 Cement CO2 1.3845699999999999
2012 Coal CO2 14.92276
2012 Gas CO2 6.500594
2012 Oil CO2 11.541707
2012 Flaring CO2 0.380351
2012 Other Industry CO2 0.276285
2013 Cement CO2 1.444086
2013 Coal CO2 15.024486000000001
2013 Gas CO2 6.542527
2013 Oil CO2 11.626445
2013 Flaring CO2 0.387535
2013 Other Industry CO2 0.29412099999999997
2014 Cement CO2 1.4999120000000001
2014 Coal CO2 15.051513000000002
2014 Gas CO2 6.654555
2014 Oil CO2 11.678782
2014 Flaring CO2 0.38790199999999997
2014 Other Industry CO2 0.30487000000000003
2015 Cement CO2 1.4444359999999998
2015 Coal CO2 14.710087999999999
2015 Gas CO2 6.788074
2015 Oil CO2 11.929665000000002
2015 Flaring CO2 0.383534
2015 Other Industry CO2 0.302769
2016 Cement CO2 1.487617

2016 Coal CO2 14.360605
2016 Gas CO2 6.973649
2016 Oil CO2 12.023833
2016 Flaring CO2 0.37838499999999997
2016 Other Industry CO2 0.300104
2017 Cement CO2 1.507923
2017 Coal CO2 14.506974
2017 Gas CO2 7.144928
2017 Oil CO2 12.242628
2017 Flaring CO2 0.391992
2017 Other Industry CO2 0.302294
2018 Cement CO2 1.569218
2018 Coal CO2 14.746831
2018 Gas CO2 7.529847
2018 Oil CO2 12.266017
2018 Flaring CO2 0.412116
2018 Other Industry CO2 0.302479
2019 Cement CO2 1.617507
2019 Coal CO2 14.725978
2019 Gas CO2 7.647528
2019 Oil CO2 12.345653
2019 Flaring CO2 0.43925400000000003
2019 Other Industry CO2 0.306639
2020 Cement CO2 1.637537
2020 Coal CO2 14.174564
2020 Gas CO2 7.55629
2020 Oil CO2 11.191809
2020 Flaring CO2 0.407584
2020 Other Industry CO2 0.296302
2021 Cement CO2 1.672592
2021 Coal CO2 14.979598
2021 Gas CO2 7.92183
2021 Oil CO2 11.837159
2021 Flaring CO2 0.416526
2021 Other Industry CO2 0.296146

In [94]:
line_world_co2 = pd.DataFrame({
    'Year':years,
    'Factor':factors,
    'Value':values
})
line_world_co2

      Year              Factor      Value
0     1750          Cement CO2   0.000000
1     1750            Coal CO2   0.009351
2     1750             Gas CO2   0.000000
3     1750             Oil CO2   0.000000
4     1750         Flaring CO2   0.000000
...    ...                 ...        ...
1627  2021            Coal CO2  14.979598
1628  2021             Gas CO2   7.921830
1629  2021             Oil CO2  11.837159
1630  2021         Flaring CO2   0.416526
1631  2021  Other Industry CO2   0.296146

[1632 rows x 3 columns]

Preparing `world_co2` for bar chart

In [95]:
coal_list = []
oil_list = []
gas_list = []
cement_list = []
flaring_list = []
ot_list = []

for i in range(len(world_co2)):
    coal_list.append(world_co2['Coal CO2'][i] / 1000)
    oil_list.append(world_co2['Oil CO2'][i] / 1000)
    gas_list.append(world_co2['Gas CO2'][i]/ 1000)
    cement_list.append(world_co2['Cement CO2'][i]/ 1000)
    flaring_list.append(world_co2['Flaring CO2'][i]/ 1000)
    ot_list.append(world_co2['Other Industry CO2'][i]/ 1000)
    
bar_world_co2 = pd.DataFrame(
    {
        'Name':world_co2.Name,
        'Year':world_co2.Year,
        'Coal CO2':coal_list,
        'Oil CO2':oil_list,
        'Gas CO2':gas_list,
        'Cement CO2':cement_list,
        'Flaring CO2':flaring_list,
        'Other Industry CO2':ot_list
    }
)
bar_world_co2

,Name,Year,Coal CO2,Oil CO2,Gas CO2,Cement CO2,Flaring CO2,Other Industry CO2
0,World,1750,0.009351,0.000000,0.000000,0.000000,0.000000,0.000000
1,World,1751,0.009351,0.000000,0.000000,0.000000,0.000000,0.000000
2,World,1752,0.009354,0.000000,0.000000,0.000000,0.000000,0.000000
3,World,1753,0.009354,0.000000,0.000000,0.000000,0.000000,0.000000
4,World,1754,0.009358,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
267,World,2017,14.506974,12.242628,7.144928,1.507923,0.391992,0.302294
268,World,2018,14.746831,12.266017,7.529847,1.569218,0.412116,0.302479
269,World,2019,14.725978,12.345653,7.647528,1.617507,0.439254,0.306639
270,World,2020,14.174564,11.191809,7.556290,1.637537,0.407584,0.296302
271,World,2021,14.979598,11.837159,7.921830,1.672592,0.416526,0.296146

Global temperature anomaly in the world - annual basis

In [62]:
global_temp = global_temp.rename(columns = {'Entity':'Name', 'Temperature anomaly' : 'Temp Anomaly'})

In [63]:
global_temp

      Name  Year  Temp Anomaly
0    World  1880     -0.166667
1    World  1881     -0.082500
2    World  1882     -0.110000
3    World  1883     -0.174167
4    World  1884     -0.280000
..     ...   ...           ...
139  World  2019      0.976667
140  World  2020      1.017500
141  World  2021      0.844167
142  World  2022      0.891667
143  World  2023      0.915000

[144 rows x 3 columns]

### Exporting the datasets

Run the code below to export the datasets in the local folder

In [100]:
total_ghg_country.to_csv('rendered/factors/total_ghg_country.csv', index=False)
perCapita_ghg_country.to_csv('rendered/factors/perCapita_ghg_country.csv', index=False)
weather_related_dis.to_csv('rendered/effects/weather_related_dis.csv', index=False)

#emissions per fossil fuel
bar_world_co2.to_csv('rendered/factors/bar_world_co2.csv', index=False)
line_world_co2.to_csv('rendered/factors/line_world_co2.csv', index=False)

global_temp.to_csv('rendered/factors/global_temp.csv', index=False)

In [97]:
bar_world_co2

,Name,Year,Coal CO2,Oil CO2,Gas CO2,Cement CO2,Flaring CO2,Other Industry CO2
0,World,1750,0.009351,0.000000,0.000000,0.000000,0.000000,0.000000
1,World,1751,0.009351,0.000000,0.000000,0.000000,0.000000,0.000000
2,World,1752,0.009354,0.000000,0.000000,0.000000,0.000000,0.000000
3,World,1753,0.009354,0.000000,0.000000,0.000000,0.000000,0.000000
4,World,1754,0.009358,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
267,World,2017,14.506974,12.242628,7.144928,1.507923,0.391992,0.302294
268,World,2018,14.746831,12.266017,7.529847,1.569218,0.412116,0.302479
269,World,2019,14.725978,12.345653,7.647528,1.617507,0.439254,0.306639
270,World,2020,14.174564,11.191809,7.556290,1.637537,0.407584,0.296302
271,World,2021,14.979598,11.837159,7.921830,1.672592,0.416526,0.296146