In [2]:
import pandas as pd

In [10]:
total_ghg = pd.read_csv('datasets/factors/owid-co2-data.csv')
total_ghg_meta = pd.read_csv('datasets/factors/owid-co2-codebook.csv')

In [5]:
total_ghg

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1850,AFG,3752993.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.121,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1851,AFG,3769828.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.118,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1852,AFG,3787706.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.116,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1853,AFG,3806634.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.115,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1854,AFG,3825655.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.114,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46518,Zimbabwe,2017,ZWE,14751101.0,2.194784e+10,0.469,0.032,9.596,-0.937,-8.899,...,NaN,0.0,0.0,0.219,0.026,NaN,115.59,28.30,0.910,9.486
46519,Zimbabwe,2018,ZWE,15052191.0,2.271535e+10,0.558,0.037,11.795,2.199,22.920,...,NaN,0.0,0.0,0.211,0.033,NaN,118.22,30.83,0.771,6.537
46520,Zimbabwe,2019,ZWE,15354606.0,NaN,0.570,0.037,11.115,-0.681,-5.772,...,NaN,0.0,0.0,0.183,0.030,NaN,117.96,30.53,0.978,8.795
46521,Zimbabwe,2020,ZWE,15669663.0,NaN,0.570,0.036,10.608,-0.507,-4.559,...,NaN,0.0,0.0,0.194,0.030,NaN,NaN,NaN,1.006,9.481
46522,Zimbabwe,2021,ZWE,15993525.0,NaN,0.570,0.036,11.296,0.688,6.488,...,NaN,0.0,0.0,0.190,0.030,NaN,NaN,NaN,NaN,NaN

In [16]:
total_ghg[['country', 'iso_code', 'year', 'total_ghg', 'ghg_per_capita']].dropna()

           country iso_code  year  total_ghg  ghg_per_capita
140    Afghanistan      AFG  1990       9.58           0.896
141    Afghanistan      AFG  1991       9.81           0.913
142    Afghanistan      AFG  1992       9.03           0.749
143    Afghanistan      AFG  1993       9.11           0.651
144    Afghanistan      AFG  1994       9.15           0.592
...            ...      ...   ...        ...             ...
46516     Zimbabwe      ZWE  2015      42.30           2.988
46517     Zimbabwe      ZWE  2016     115.92           8.021
46518     Zimbabwe      ZWE  2017     115.59           7.836
46519     Zimbabwe      ZWE  2018     118.22           7.854
46520     Zimbabwe      ZWE  2019     117.96           7.682

[5789 rows x 5 columns]

In [15]:
for each in total_ghg_meta['column']:
    print(each)

country
year
iso_code
population
gdp
cement_co2
cement_co2_per_capita
co2
co2_growth_abs
co2_growth_prct
co2_including_luc
co2_including_luc_growth_abs
co2_including_luc_growth_prct
co2_including_luc_per_capita
co2_including_luc_per_gdp
co2_including_luc_per_unit_energy
co2_per_capita
co2_per_gdp
co2_per_unit_energy
coal_co2
coal_co2_per_capita
consumption_co2
consumption_co2_per_capita
consumption_co2_per_gdp
cumulative_cement_co2
cumulative_co2
cumulative_co2_including_luc
cumulative_coal_co2
cumulative_flaring_co2
cumulative_gas_co2
cumulative_luc_co2
cumulative_oil_co2
cumulative_other_co2
energy_per_capita
energy_per_gdp
flaring_co2
flaring_co2_per_capita
gas_co2
gas_co2_per_capita
ghg_excluding_lucf_per_capita
ghg_per_capita
land_use_change_co2
land_use_change_co2_per_capita
methane
methane_per_capita
nitrous_oxide
nitrous_oxide_per_capita
oil_co2
oil_co2_per_capita
other_co2_per_capita
other_industry_co2
primary_energy_consumption
share_global_cement_co2
share_global_co2
share_global_co2_including_luc
share_global_coal_co2
share_global_cumulative_cement_co2
share_global_cumulative_co2
share_global_cumulative_co2_including_luc
share_global_cumulative_coal_co2
share_global_cumulative_flaring_co2
share_global_cumulative_gas_co2
share_global_cumulative_luc_co2
share_global_cumulative_oil_co2
share_global_cumulative_other_co2
share_global_flaring_co2
share_global_gas_co2
share_global_luc_co2
share_global_oil_co2
share_global_other_co2
total_ghg
total_ghg_excluding_lucf
trade_co2
trade_co2_share